spring.application.name: payments

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:switchwon-db
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath*:db/data.sql
h2:
  console:
    enabled: true
    path: /h2-console
